#!/bin/sh

# Convert Debian Stable to Testing

cat > /etc/apt/sources.list <<EOF
deb http://deb.debian.org/debian testing main contrib non-free

deb http://security.debian.org/debian-security testing-security main contrib non-free

deb http://deb.debian.org/debian testing-updates main contrib non-free
EOF

apt update
apt -y install wget curl git vim
apt -y upgrade 
apt -y dist-upgrade
apt -y autoremove
apt -y clean

# systemd-networkd
# systemctl --type=service
DEVICENAME="$(ip -o -4 route show to default | awk '{print $5}')"

cat> /etc/systemd/network/dhcp.network<<EOF
[Match]
Name=${DEVICENAME} 

[Network]
DHCP=yes
EOF

systemctl enable systemd-networkd --now

# systemd-resolved
echo "DNS=1.1.1.1" >> /etc/systemd/resolved.conf
echo "DNS=2606:4700:4700::1111" >> /etc/systemd/resolved.conf
systemctl enable systemd-resolved


echo "Please reboot"
# remove debian's buildin network manager
apt -y remove ifupdown
