#!/bin/sh

# Convert Debian Stable to Testing

cat > /etc/apt/sources.list <<EOF
deb http://deb.debian.org/debian testing main contrib non-free

deb http://security.debian.org/debian-security testing-security main contrib non-free

deb http://deb.debian.org/debian testing-updates main contrib non-free
EOF

apt update
apt -y install wget curl git vim
apt -y upgrade 
apt -y dist-upgrade
apt -y autoremove
apt -y clean
