#!/bin/bash

# Pre 
# bash <(wget -qO- https://raw.githubusercontent.com/bohanyang/debi/master/debi.sh) --user root  --authorized-keys-url https://github.com/mlyxshi.keys --version stable --filesystem ext4 &&reboot

if [ -z $1 ] 
then
# Convert Debian Stable to Testing
cat > /etc/apt/sources.list <<EOF
deb http://deb.debian.org/debian testing main contrib non-free
deb http://security.debian.org/debian-security testing-security main contrib non-free
deb http://deb.debian.org/debian testing-updates main contrib non-free
EOF
elif [ $1 = "sid" ]
then
# Convert Debian Stable to Unstable
cat > /etc/apt/sources.list <<EOF
deb http://deb.debian.org/debian/ sid main contrib non-free
EOF
fi

apt update
apt -y install wget curl git vim neovim unzip
apt -y upgrade 
apt -y dist-upgrade
apt -y autoremove
apt -y clean

# nerd font(Hack)
cd ~
wget https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/Hack.zip
unzip Hack.zip -d /usr/share/fonts/
fc-cache -fv



# systemd-networkd
DEVICENAME="$(ip -o -4 route show to default | awk '{print $5}'|head -1)"

cat> /etc/systemd/network/dhcp.network<<EOF
[Match]
Name=${DEVICENAME} 

[Network]
DHCP=yes
EOF

systemctl enable systemd-networkd 

# systemd-resolved
echo "DNS=1.1.1.1" >> /etc/systemd/resolved.conf
echo "DNS=2606:4700:4700::1111" >> /etc/systemd/resolved.conf
systemctl enable systemd-resolved


# systemctl --type=service
# remove debian's buildin network manager
apt purge -y --auto-remove ifupdown isc-dhcp-client

#Under chroot environment, OS can not reboot, which is what we want[configure other thing like systemd-boot]
#Under normal environment, OS need reboot
reboot
