#!/bin/sh

apt -y install firmware-linux-nonfree
apt -y --no-install-recommends install gnome-core

# gnome42 add RDP (Need more test)
# apt -y install gnome-remote-desktop
# systemctl --user start gnome-remote-desktop

#vscode
apt -y install wget gpg
wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > packages.microsoft.gpg
install -o root -g root -m 644 packages.microsoft.gpg /etc/apt/trusted.gpg.d/
echo "deb [arch=amd64,arm64 signed-by=/etc/apt/trusted.gpg.d/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main" > /etc/apt/sources.list.d/vscode.list
rm -f packages.microsoft.gpg
apt update
apt install -y code 
