#!/bin/bash

apt -y install firmware-linux-nonfree fonts-wqy-microhei
apt -y --no-install-recommends install gnome-core gnome-console mpv ranger
# Remove Gnome Build-in App
# https://packages.debian.org/sid/gnome-core
# Video Player totem     ->mpv
# Image Viewer eog       ->ranger
# File Browser nautilus  ->ranger
apt purge --auto-remove totem eog nautilus gnome-calculator gnome-contacts gnome-text-editor gnome-software gnome-terminal

# gnome42 add RDP (Need more test)
# apt -y install gnome-remote-desktop
# systemctl --user start gnome-remote-desktop

# replace gnome-console with warp, when warp(linux) releases 

#vscode
if [ $(uname -m) = "x86_64" ]
then
  echo "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main" > /etc/apt/sources.list.d/vscode.list
elif [ $(uname -m) = "aarch64" ]
then
  echo "deb [arch=arm64 signed-by=/etc/apt/trusted.gpg.d/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main" > /etc/apt/sources.list.d/vscode.list
else
  exit 1
fi

apt -y install wget gpg
wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > packages.microsoft.gpg
install -o root -g root -m 644 packages.microsoft.gpg /etc/apt/trusted.gpg.d/
rm -f packages.microsoft.gpg
apt update
apt install -y code 
