#!/bin/sh

apt update
apt -y upgrade 

Green='\033[0;32m' 
Yellow='\033[0;33m'

# cat need escape $
cat > /etc/kernel/postinst.d/zz-update-systemd-boot <<EOF
#!/bin/sh

/usr/bin/kernel-install add "\$1" "\$2"
echo -e "${Green}Systemd-boot Add Entry Success"
exit 0
EOF

chmod 755 /etc/kernel/postinst.d/zz-update-systemd-boot

cat > /etc/kernel/postrm.d/zz-update-systemd-boot <<EOF
#!/bin/sh

/usr/bin/kernel-install remove "\$1"
echo -e "${Green}Systemd-boot Remove Entry Success"
exit 0
EOF

chmod 755 /etc/kernel/postrm.d/zz-update-systemd-boot

MACHINE_ID=$(cat /etc/machine-id)
ESP_PATH=$(bootctl -p)

bootctl install 
mkdir ${ESP_PATH}/${MACHINE_ID}


cat > ${ESP_PATH}/loader/loader.conf<<EOF
timeout 2
EOF


# very ugly way to get latest installed kernel package name 
KERNEL_PACKAGE=$(dpkg -l|awk '{print $2}'|grep linux-image|sed 's/linux-image-amd64//'|sed 's/linux-image-arm64//'|sort -r|head -1)

# manually trigger postinst.d script to run kernel-install
# kernel-install move /boot/vmlinuz /boot/initrd to ESP:/MACHINEID.
# and add entry in ESP:/loader/entries
apt -y reinstall ${KERNEL_PACKAGE}

apt -y remove grub*
apt install efibootmgr
apt -y autoremove
efibootmgr

echo -e "${Yellow}Please Manually Configure Boot Order"
echo -e "${Yellow}efibootmgr -b <X> -B"
